---
- name: install apt dependencies
  apt:
    name: "{{ py_apt_deps }}"

- name: ensure install and sources dir exist
  file:
    path: "{{ item }}"
    state: directory
  loop:
    - "{{ _py_install_dir }}"
    - "{{ _py_sources_dir }}"

- name: download package
  unarchive:
    remote_src: true
    src: "https://www.python.org/ftp/python/{{ py_version }}/Python-{{ py_version }}.tgz"
    dest: "{{ _py_sources_dir }}"
    extra_opts: [--strip-components=1]  # Needed since the sources are packed inside a folder named PythonX.Y.Z
    creates: "{{ _py_sources_dir }}/configure"

- name: configure
  command: "./configure --prefix={{ _py_install_dir }}"
  args:
    chdir: "{{ _py_sources_dir }}"
    creates: "{{ _py_sources_dir }}/Makefile"

- name: make
  make:
    chdir: "{{ _py_sources_dir }}"
  environment:
    MAKEFLAGS: "-j{{ ansible_processor_vcpus }}"
  changed_when: false

- name: make altinstall
  make:
    chdir: "{{ _py_sources_dir }}"
    target: altinstall
  environment:
    MAKEFLAGS: "-j{{ ansible_processor_vcpus }}"
  changed_when: false
